language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  - COMPOSER_FLAGS="--prefer-stable"

php:
  - 7.1

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION="^2.8"
    - php: 7.0
      env: WITHOUT_EXTRA_BUNDLE=1
    - php: 7.1
      env: SYMFONY_VERSION="^3.4"
    - php: 7.1
      env: SYMFONY_VERSION="^4.0"
    - script: vendor/bin/phpcs -n
      env: PHPCS_BUILD=1
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"

before_install:
    - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi
    - if [[ "$WITHOUT_EXTRA_BUNDLE" != "" ]]; then composer remove "sensio/framework-extra-bundle" --dev; fi;

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
